### ISSUE TITLE
Rearrange/Edit navigation bar 

### ISSUE THREAD

**Issue by alphatrl** [bottleneckco/thinking-minecraft#2]
<img width="560" alt="rearrange-navigation" src="https://user-images.githubusercontent.com/8110786/32133613-04749dfe-bc0e-11e7-8387-f144e43b93fc.png">

Feel that "Home" should be the first link, instead of arranging the links alphabetically.
If rearranged, what should be the new order as well?
* Home
* Hello
* About
* Posts

@duncanleo @chesterhow

**Comment by duncanleo** [comment]
How about shortening the content in About and then placing all the Home content below the shortened text (and making that the home page)?

**Comment by chesterhow** [comment]
I think you can combine About and hello!. They’re kinda the same thing

**Comment by alphatrl** [comment]
Okay. Will merge the 2 pages together

Amos Tan

**Comment by alphatrl** [comment]
https://github.com/bottleneckco/thinking-minecraft/pull/3
